def writesetfields(setFieldsLocation,wnum,L,det):
    pass
#     with open(setFieldsLocation,'w') as setfields:
#         setfields.write('/*--------------------------------*- C++ -*----------------------------------  \n')
#         setfields.write('| =========                 |                                                 |\n')
#         setfields.write('| \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox           |\n')
#         setfields.write('|  \\    /   O peration     | Version:  1.7.1                                 |\n')
#         setfields.write('|   \\  /    A nd           | Web:      www.OpenFOAM.com                      |\n')
#         setfields.write('|    \\/     M anipulation  |                                                 |\n')
#         setfields.write('  ---------------------------------------------------------------------------*/\n')
#         setfields.write('FoamFile\n')
#         setfields.write('{\n')
#         setfields.write('    version     2.0;\n')
#         setfields.write('    format      ascii;\n')
#         setfields.write('    class       dictionary;\n')
#         setfields.write('    location    "system";\n')
#         setfields.write('    object      setFieldsDict;\n')
#         setfields.write('}\n')
#         setfields.write('// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //\n')
#         setfields.write('\n')
#         setfields.write('defaultFieldValues\n')
#         setfields.write('(\n')
#         setfields.write('    volScalarFieldValue alpha1 0\n')
#         setfields.write(');\n')
#         setfields.write('\n')
#         setfields.write('regions\n')
#         setfields.write('(\n')
#         setfields.write('    boxToCell\n')
#         setfields.write('    {\n')
#         setfields.write('        box (0 -0.002 -1) (%10.8f %10.8f 1);\n'% (wnum*L,det))?
#         setfields.write('        fieldValues\n')
#         setfields.write('        (\n')
#         setfields.write('            volScalarFieldValue alpha1 1\n')
#         setfields.write('        );\n')
#         setfields.write('    }\n')
#         setfields.write(');\n')
#         setfields.write('// ************************************************************************* //\n')